headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\Claude 安装\\UPS选型助手_开发包_v1.2\\UPS选型助手_开发包_v1.2"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/"
to = "/UPS选型助手.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]