import sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8')
all_ok = True

PROJECT_ROOT = Path(__file__).resolve().parents[1]

with open(PROJECT_ROOT / 'index.html', encoding='utf-8') as f:
    html = f.read()

checks = [
    ('双表HTML-上栏', 'db-table-top'),
    ('双表HTML-下栏', 'db-table-bot'),
    ('双表分栏容器', 'id="db-split-layout"'),
    ('可拖动分隔条', 'id="db-splitter"'),
    ('分隔条初始化', 'function initDatabaseSplitter'),
    ('双表横向拖动', 'function initDatabaseHorizontalDrag'),
    ('横向拖动不拦截文字选择', 'event.button === 0 && event.shiftKey'),
    ('文字选择交互提示', '可选择文字；按住 Shift 拖动可横向查看'),
    ('列宽拖动功能', 'function initDatabaseColumnResizer'),
    ('列宽拖动提示', '拖动列宽 · Shift+拖动横移'),
    ('型号详情弹窗', 'id="db-detail-modal"'),
    ('型号详情打开逻辑', 'function openDatabaseProductDetail'),
    ('型号详情产品信息卡片', 'db-detail-product-grid'),
    ('型号详情泰尔参数卡片', 'db-detail-tech-grid'),
    ('产品收藏筛选入口', 'id="db-favorites-filter"'),
    ('产品收藏本地持久化', "const DB_FAVORITES_STORAGE_KEY = 'ups_db_favorites_v1'"),
    ('产品收藏切换逻辑', 'function toggleDatabaseFavorite'),
    ('UPS目录价严格匹配表', 'const UPS_CATALOG_ENRICHMENTS'),
    ('UPS目录价回填逻辑', 'function enrichProductsWithCatalog'),
    ('目录价同时校验型号与描述', 'normalizeCatalogMatchText(item.model) + "|" + normalizeCatalogMatchText(item.description)'),
    ('持久化数据目录价回填', 'const catalogMatchCount = enrichProductsWithCatalog(PRODUCTS)'),
    ('目录价版本字段', 'product["目录价版本"] = "iTeaQ-2026-04-V1.0"'),
    ('产品编码仅保留8位数字', '产品编码列只保存 PDF 中的 8 位数字'),
    ('产品编码区分机柜与功率模块', 'function formatUpsCatalogCodeDisplay'),
    ('收藏筛选逻辑', "dbFavoritesOnly && !isDatabaseFavorite"),
    ('详情卡片收藏入口', 'id="db-detail-favorite"'),
    ('文字选择不触发行详情', 'selection && !selection.isCollapsed'),
    ('横向平移不误触详情', "scroller.dataset.suppressRowClick = 'true'"),
    ('多套UPS配置管理区', 'id="multi-ups-list"'),
    ('保存并新增下一套', 'function saveCurrentUpsConfigurationAndStartNext'),
    ('新配置按钮定位表单', "showImportToast('已开始新配置，请选择或填写 UPS 型号')"),
    ('空UPS型号禁止加入项目', "请先选择 UPS 型号，再加入项目"),
    ('UPS型号关键字搜索框', 'id="ups-model-search-results"'),
    ('UPS型号实时过滤', 'function getFilteredUpsModels'),
    ('UPS型号键盘选择', 'function handleUpsModelSearchKeydown'),
    ('UPS型号必须完整选择', '请从匹配结果中选择完整的 UPS 型号'),
    ('空UPS型号允许计算', 'function getUpsCalculationModelError'),
    ('监控主机显示屏计算方式下拉框', 'id="unified-monitor-basis"'),
    ('监控主机显示屏按组数或UPS台数计算', 'function getMonitorHostCalculation'),
    ('监控计算方式随配置保存', "'unified-switch-basis', 'unified-monitor-basis'"),
    ('开关计算成本影响提示', 'id="switch-cost-impact"'),
    ('监控数量成本影响提示', 'id="monitor-cost-impact"'),
    ('电池开关成本影响提示', 'id="switch-type-cost-impact"'),
    ('中性线模块说明', 'id="neutral-module-note"'),
    ('产品详情浮窗拖动手柄', 'id="db-detail-drag-handle"'),
    ('产品详情浮窗拖动逻辑', 'function initDatabaseDetailDrag'),
    ('产品详情浮窗背景可操作', '#db-detail-modal { display:none;position:fixed;inset:0;z-index:1150;pointer-events:none; }'),
    ('产品详情浏览器独立窗口按钮', 'id="db-detail-popout"'),
    ('产品详情浏览器独立窗口逻辑', 'function openDatabaseProductPopout'),
    ('独立窗口支持四边缩放与滚动', 'resizable=yes,scrollbars=yes'),
    ('独立窗口随主页面型号同步', 'renderDatabaseProductPopout(product)) return'),
    ('已有结果切换型号自动重算', 'if (window.projectSummary?.generatedAt) calcAllBatteryConfig();'),
    ('配置参数修改提示重算', 'function markUnifiedConfigurationDirty'),
    ('UPS目录字段进入汇总', 'function getUpsCatalogSummaryDefaults'),
    ('多机框版本UPS识别模块', 'parts.length >= 2 && /-M\\d*$/.test(parts[parts.length - 1])'),
    ('汇总固定成品按产品身份合并', "const fixedCatalogCategories = ['UPS', 'UPS机框', '功率模块', '电池', '电池监控']"),
    ('汇总差异描述换行保留', "entry.desc = entry.descriptions.join('\\n')"),
    ('汇总使用产品完整描述', "upsProduct?.['描述']"),
    ('汇总表列宽拖动', 'function initSummaryColumnResizers'),
    ('汇总表横向滚动', 'id="project-summary-scroll"'),
    ('汇总表业务顺序', 'function sortSummaryRowsByBusinessOrder'),
    ('汇总表手动顺序标记', 'rowOrderCustomized'),
    ('汇总行鼠标拖拽手柄', 'class="summary-row-drag-handle"'),
    ('汇总行拖放排序', 'function handleSummaryRowDrop'),
    ('汇总行拖放落点提示', 'summary-row-drop-before'),
    ('汇总自定义行Excel批量粘贴', 'function handleCustomSummaryPaste'),
    ('汇总粘贴自动补行', 'function applyCustomSummaryPasteMatrix'),
    ('汇总粘贴跳过小计列', "'unitPrice', null, 'nonStandardDesc'"),
    ('汇总描述框自动增高', 'function autoResizeSummaryTextarea'),
    ('汇总自动增高初始化', 'function initSummaryAutoGrowTextareas'),
    ('载入已保存配置', 'function loadSavedUpsConfiguration'),
    ('相同物料自动合并', 'function collectSavedConfigurationRows'),
    ('配置型物料规格化合并键', 'function getSavedSummaryAggregationIdentity'),
    ('汇总合并规则界面提示', '仅在型号及配置规格均一致时合并数量'),
    ('多配置导出链路', 'collectProjectSummaryRows({ includeSaved: false })'),
    ('数据库视图占满剩余高度', 'body.db-view-active #data-table-panel'),
    ('数据库视图状态切换', "document.body.classList.toggle('db-view-active', key === 'db')"),
    ('产品信息标签', '产品信息'),
    ('泰尔规格标签', '技术规格（泰尔参数）'),
    ('DB_TOP_SET', 'const DB_TOP_SET'),
    ('buildTableHead', 'function buildTableHead'),
    ('buildRow', 'function buildRow'),
    ('悬停联动', 'db-row-hover'),
    ('sortDataTable双section', 'dbSortSection'),
    ('搜索高亮正则转义', 'keyword.replace(/[.*+?^${}()|['),
]
for name, key in checks:
    found = key in html
    mark = 'OK' if found else 'XX'
    print(f'  [{mark}] {name}')
    all_ok = all_ok and found

raise SystemExit(0 if all_ok else 1)
